# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
    - libprotobuf-dev
    - libprotobuf9v5
    - libzmq-dev
    - libzmq5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
