# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='internal.proto',
  package='lte.internal',
  serialized_pb=_b('\n\x0einternal.proto\x12\x0clte.internal\"\n\n\x08TimerInd')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TIMERIND = _descriptor.Descriptor(
  name='TimerInd',
  full_name='lte.internal.TimerInd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=42,
)

DESCRIPTOR.message_types_by_name['TimerInd'] = _TIMERIND

TimerInd = _reflection.GeneratedProtocolMessageType('TimerInd', (_message.Message,), dict(
  DESCRIPTOR = _TIMERIND,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:lte.internal.TimerInd)
  ))
_sym_db.RegisterMessage(TimerInd)


# @@protoc_insertion_point(module_scope)
