# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lte.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import s1ap_pb2
import x2ap_pb2
import rrc_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lte.proto',
  package='lte',
  serialized_pb=_b('\n\tlte.proto\x12\x03lte\x1a\ns1ap.proto\x1a\nx2ap.proto\x1a\trrc.proto\"j\n\x04\x41SN1\x12\x1e\n\x04s1ap\x18\x01 \x01(\x0b\x32\x0e.lte.s1ap.S1APH\x00\x12\x1e\n\x04x2ap\x18\x02 \x01(\x0b\x32\x0e.lte.x2ap.X2APH\x00\x12\x1b\n\x03rrc\x18\x03 \x01(\x0b\x32\x0c.lte.rrc.RRCH\x00\x42\x05\n\x03msg')
  ,
  dependencies=[s1ap_pb2.DESCRIPTOR,x2ap_pb2.DESCRIPTOR,rrc_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ASN1 = _descriptor.Descriptor(
  name='ASN1',
  full_name='lte.ASN1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s1ap', full_name='lte.ASN1.s1ap', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x2ap', full_name='lte.ASN1.x2ap', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rrc', full_name='lte.ASN1.rrc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='lte.ASN1.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=53,
  serialized_end=159,
)

_ASN1.fields_by_name['s1ap'].message_type = s1ap_pb2._S1AP
_ASN1.fields_by_name['x2ap'].message_type = x2ap_pb2._X2AP
_ASN1.fields_by_name['rrc'].message_type = rrc_pb2._RRC
_ASN1.oneofs_by_name['msg'].fields.append(
  _ASN1.fields_by_name['s1ap'])
_ASN1.fields_by_name['s1ap'].containing_oneof = _ASN1.oneofs_by_name['msg']
_ASN1.oneofs_by_name['msg'].fields.append(
  _ASN1.fields_by_name['x2ap'])
_ASN1.fields_by_name['x2ap'].containing_oneof = _ASN1.oneofs_by_name['msg']
_ASN1.oneofs_by_name['msg'].fields.append(
  _ASN1.fields_by_name['rrc'])
_ASN1.fields_by_name['rrc'].containing_oneof = _ASN1.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['ASN1'] = _ASN1

ASN1 = _reflection.GeneratedProtocolMessageType('ASN1', (_message.Message,), dict(
  DESCRIPTOR = _ASN1,
  __module__ = 'lte_pb2'
  # @@protoc_insertion_point(class_scope:lte.ASN1)
  ))
_sym_db.RegisterMessage(ASN1)


# @@protoc_insertion_point(module_scope)
