# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: s1ap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='s1ap.proto',
  package='lte.s1ap',
  serialized_pb=_b('\n\ns1ap.proto\x12\x08lte.s1ap\"\x06\n\x04S1AP')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_S1AP = _descriptor.Descriptor(
  name='S1AP',
  full_name='lte.s1ap.S1AP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=30,
)

DESCRIPTOR.message_types_by_name['S1AP'] = _S1AP

S1AP = _reflection.GeneratedProtocolMessageType('S1AP', (_message.Message,), dict(
  DESCRIPTOR = _S1AP,
  __module__ = 's1ap_pb2'
  # @@protoc_insertion_point(class_scope:lte.s1ap.S1AP)
  ))
_sym_db.RegisterMessage(S1AP)


# @@protoc_insertion_point(module_scope)
