# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: x2ap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='x2ap.proto',
  package='lte.x2ap',
  serialized_pb=_b('\n\nx2ap.proto\x12\x08lte.x2ap\"\x06\n\x04X2AP')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_X2AP = _descriptor.Descriptor(
  name='X2AP',
  full_name='lte.x2ap.X2AP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=30,
)

DESCRIPTOR.message_types_by_name['X2AP'] = _X2AP

X2AP = _reflection.GeneratedProtocolMessageType('X2AP', (_message.Message,), dict(
  DESCRIPTOR = _X2AP,
  __module__ = 'x2ap_pb2'
  # @@protoc_insertion_point(class_scope:lte.x2ap.X2AP)
  ))
_sym_db.RegisterMessage(X2AP)


# @@protoc_insertion_point(module_scope)
